[package]
name = "rung"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2018"

[dependencies]
ureq = { version = "0.12.0", features = ["json", "tls"] }
confy = "0.4.0"
serde_derive = "1.0.105"
serde = "1.0.105"
