[package]
name = "rung"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2021"

[dependencies]
ureq = { version = "2.5.0", features = ["json", "tls"] }
confy = "0.5.1"
serde = "1.0.125"
serde_derive = "1.0.125"
