[package]
name = "rung"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2018"

[dependencies]
ureq = { version = "2.0.1", features = ["json", "tls"] }
confy = "0.4.0"
serde = "1.0.122"
serde_derive = "1.0.123"
