[package]
name = "rung"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2018"

[dependencies]
ureq = { version = "*", features = ["json", "tls"] }
confy = "0.3.1"
serde_derive = "1.0.102"
serde = "1.0.101"
